### ISSUE TITLE
Complatible with Styled-componets

### ISSUE THREAD

**Issue by lucasdzuc** [Aslam97/shadcn-minimal-tiptap#42]
Can I use this package in a project that uses styled-components?

**Comment by Aslam97** [comment]
@lucasdzuc The editor uses Tailwind and a CSS file for styling the content, so that won't be an issue. The only thing to consider is that this editor uses components from ShadCN, but you can always grab those components manually and customize them to your needs to suite with styled-components.

**Comment by Aslam97** [comment]
@lucasdzuc What I would suggest is:

1. Install Shadcn manually throught this link https://ui.shadcn.com/docs/installation/manual
2. Copy all the components that required in order to run this package https://github.com/Aslam97/shadcn-minimal-tiptap?tab=readme-ov-file#dependencies
3. Register the TooltipProvider https://github.com/Aslam97/shadcn-minimal-tiptap?tab=readme-ov-file#installation
4. Customize the components, css to suite your need

Shadcn/ui is not a package, rather its just a code with extra style on it. so dont too confuse with the package name that this can only be use with Shadcn/ui

**Comment by lucasdzuc** [comment]
@Aslam97  I see, do I need to install Tailwind and configure it as well?

**Comment by Aslam97** [comment]
@lucasdzuc Yes, u should install Tailwind and if still needed, u can convert it to styled-components. However, Why not use Tailwind alongside styled-components? Tailwind only compiles the classes you actually use, making it efficient.

**Comment by Aslam97** [comment]
Hi @lucasdzuc I will close this issue for now. feel free to open this issue again, if you have any more question
