### ISSUE TITLE
Answer Needed: can we use this in nextJS with other design systems e.g antd?

### ISSUE THREAD

**Issue by hanzlahabib** [Aslam97/shadcn-minimal-tiptap#54]

**Comment by Aslam97** [comment]
@hanzlahabib You can use it with Next.js. While it's not compatible with Ant Design, you can maintain separate component systems. Since Shadcn/UI is based on Radix, it's component-based, which means you can integrate it into your existing design system and customize the design as needed to match antd design.

**Comment by Aslam97** [comment]
@hanzlahabib Its seem that you dont more any question. I ll close this issue for now. feel free to reopen or create new issue
